---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family | lower }}.yaml"
    - "default.yaml"

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ required_packages }}"

- name: Install a Libreswan .deb package from S3
  apt:
    deb: https://pawapay-packages.s3.eu-central-1.amazonaws.com/libreswan_4.6-1_amd64.deb

- name: enable forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- name: disable default reverse path filter
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: '0'
    state: present

- name: disable current reverse path filter
  shell: |
    for i in /proc/sys/net/ipv4/conf/*/rp_filter
    do
      echo 0 > $i
    done
  changed_when: false

- name: disable accept redirects
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: '0'
    state: present

- name: disable send redirects
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: '0'
    state: present

- name: "create ipsec conf files"
  template:
    src: connection.conf
    dest: "/etc/ipsec.d/{{ item.key }}.conf"
    mode: '0644'
  loop: "{{ ipsec_connections | dict2items }}"
  notify: restart ipsec service

- name: "create ipsec secrets files"
  template:
    src: connection.secrets
    dest: "/etc/ipsec.d/{{ item.key }}.secrets"
    mode: '0600'
  loop: "{{ ipsec_connections | dict2items }}"
  notify: restart ipsec service

- name: enable and start ipsec service
  service:
    name: ipsec
    state: started
    enabled: yes
